import $ from './jquery-3.2.1.min.js'
import './bootstrap.min.js'
import './jquery-ui.min.js'
import './jquery.nicescroll.min.js'
import './jquery.slicknav.min.js'
import './jquery.zoom.min.js'
import './main.js'
import './map.js'
import './bootstrap.min.js'